# Intent and Slot classification with pretrained BERT models

trainer:
  devices: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 20
  max_steps: -1 # precedence over max_epochs
  accumulate_grad_batches: 1 # accumulates grads every k batches
  precision: 16 # Should be set to 16 for O1 and O2 amp_level to enable the AMP.
  accelerator: gpu
  strategy: auto
  log_every_n_steps: 5  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations

  enable_checkpointing: False
  logger: false  # Provided by exp_manager

model:
  nemo_path: "specialist-model" # filename to save the model and associated artifacts to .nemo file
  data_dir: ??? # /path/to/data
  class_labels:
    intent_labels_file: intent_labels.csv
    slot_labels_file: slot_labels.csv
  class_balancing: "weighted_loss" # null or weighted_loss
  intent_loss_weight: 0.3 # relation of intent to slot loss in total loss (between 0 to 1), lower means more priority in slots
  pad_label: -1 # if -1 not slot token will be used
  ignore_extra_tokens: true
  ignore_start_end: false # do not use first and last token for slot training

  train_ds:
    prefix: train
    batch_size: 8
    shuffle: true
    num_samples: -1
    num_workers: 16
    drop_last: false
    pin_memory: false

  validation_ds:
    prefix: test
    batch_size: 8
    shuffle: false
    num_samples: -1
    num_workers: 16
    drop_last: false
    pin_memory: false

  test_ds:
    prefix: test
    batch_size: 8
    shuffle: false
    num_samples: -1
    num_workers: 16
    drop_last: false
    pin_memory: false

  tokenizer:
    tokenizer_name: ${model.language_model.pretrained_model_name} # or sentencepiece
    vocab_file: null # path to vocab file
    tokenizer_model: null # only used if tokenizer is sentencepiece
    special_tokens: null

  language_model:
    max_seq_length: 128
    pretrained_model_name: bert-base-uncased
    lm_checkpoint: null
    config_file: null # json file, precedence over config
    config: null

  head:
    num_output_layers: 2
    fc_dropout: 0.25

  optim:
    name: adamw
    lr: 0.00002
    args:
      name: auto
      params:
        weight_decay: 0.0

exp_manager:
  exp_dir: null  # exp_dir for your experiment, if None, defaults to "./nemo_experiments"
  name: "specialist-matching"  # The name of your model
  create_tensorboard_logger: true  # Whether you want exp_manger to create a tb logger
  create_checkpoint_callback: true  # Whether you want exp_manager to create a modelcheckpoint callback

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
